### ISSUE TITLE
Class 'Paystack' not found 

### ISSUE THREAD

**Issue by mushkaa** [unicodeveloper/laravel-paystack#10]
hey, please am having issues integrating paystack...it keeps returning "Class 'Paystack' not found " 
![image](https://cloud.githubusercontent.com/assets/13512137/21074608/f105219e-beb1-11e6-802d-352b0fabdc17.png)

**Comment by unicodeveloper** [comment]
Are you sure the Facade and Service Provider has been registered? Did you publish them?

**Comment by mushkaa** [comment]
Yes sir... Published dem in my config/app. Php file

**Comment by unicodeveloper** [comment]
Do you also have a `paystack.php` file in your config directory?
