### ISSUE TITLE
Is this library compatible with REST implementations of Laravel logic?

### ISSUE THREAD

**Issue by KgotsoK** [unicodeveloper/laravel-paystack#121]
So I have a few Angular apps and they only hit my Laravel app through a REST API. I see most of these library methods process form input and can generate redirects etc. I would have loved to handle that in my own PWA. Are there methods that I can use to interface with paystack and simply produce JSON as a response to my PWA?

**Comment by kingzamzon** [comment]
> So I have a few Angular apps and they only hit my Laravel app through a REST API. I see most of these library methods process form input and can generate redirects etc. I would have loved to handle that in my own PWA. Are there methods that I can use to interface with paystack and simply produce JSON as a response to my PWA?

I will recommend using [Angular 4](https://www.npmjs.com/package/angular4-paystack)

**Comment by KgotsoK** [comment]
I use Angular 9 @kingzamzon. My question was really trying to establish if this library can fit in with a Laravel REST API... It doesnt matter what frontend framework I use.

**Comment by kingzamzon** [comment]
> So I have a few Angular apps and they only hit my Laravel app through a REST API. I see most of these library methods process form input and can generate redirects etc. I would have loved to handle that in my own PWA. Are there methods that I can use to interface with paystack and simply produce JSON as a response to my PWA?

It seems I haven't answer your question, here is my answer:

The package returns JSON response after payment is successful so it ought to be applicable, but you have to set the parameters from frontend in this case your angular app. :)

**Comment by KgotsoK** [comment]
Awesome, thanks @kingzamzon I am busy testing it now... was skeptical of using that Angular4paystack library as it hasnt been updated in a while and I'd like my payment logic to be on the backend only.
