### ISSUE TITLE
PSR-4 Auto loading warning

### ISSUE THREAD

**Issue by teamnovanest** [unicodeveloper/laravel-paystack#122]
I just completed the instalation of the the library and  this warining came up.
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/49978385/97092514-bed2b800-1644-11eb-95df-f88c279f882d.png">
Will it affect my integration in any way?

I use `laravel/framework v7.28.4`
`PHP 7.4.9 (cli) (built: Aug  7 2020 19:23:06) ( NTS )`

**Comment by Kennexcorp** [comment]
I am having same issue

**Comment by kingzamzon** [comment]
this error does not stop it from working..
its just the namespace.

**Comment by kingzamzon** [comment]
> I just completed the instalation of the the library and this warining came up.
> <img alt="image" width="1287" src="https://user-images.githubusercontent.com/49978385/97092514-bed2b800-1644-11eb-95df-f88c279f882d.png">
> Will it affect my integration in any way?
> 
> I use `laravel/framework v7.28.4`
> `PHP 7.4.9 (cli) (built: Aug 7 2020 19:23:06) ( NTS )`

No it won't.

**Comment by teamnovanest** [comment]
Thanks @kingzamzon ,  i will go ahead and close the issue.
