### ISSUE TITLE
Invalid plan Sent

### ISSUE THREAD

**Issue by PromiseShedrach** [unicodeveloper/laravel-paystack#125]
When I try to initialize a transaction. I get this error:

GuzzleHttp\Exception\ClientException
Client error: `POST https://api.paystack.co/transaction/initialize` resulted in a `400 Bad Request` response: { "status": false, "message": "Invalid plan Sent" }

**Comment by Raymoneto** [comment]
I encountered same issue. The payment was working seamlessly hours ago, and stopped with _Invalid plan Sent_. I had to do a quick fix by tampering with the library code.

Goto: vendor/unicodeveloper/src/Paystack.php, and comment the line below:

// "plan" => request()->plan,

NB: This is a quick fix, and shouldn't be used when implementing plans/subscriptions.

**Comment by unicodeveloper** [comment]
@PromiseShedrach @Raymoneto I have fixed the issue. Please update to the latest version of the package.

**Comment by Raymoneto** [comment]
> @PromiseShedrach @Raymoneto I have fixed the issue. Please upgrade to the latest version of the package.

Bravo! Thank you.

**Comment by blazefluz** [comment]
You don't need to comment it.

Go to the vendor folder vendor\unicodeveloper\laravel-paystack\src\Paystack.php
Change "plan" => request()->plan,
to
"plan_code" => request()->plan,

paystack did an update that is why you have an error.

**Comment by opeAlomaja** [comment]
"plan_code" => request()->plan,
or
//"plan" => request()->plan,

nothing works
