### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by goodnesskay** [unicodeveloper/laravel-paystack#14]
I got this error when I clicked on the pay button of the default form created in this package. What did I do wrong? Thanks

**Comment by unicodeveloper** [comment]
This is not from the package. This has to do with internet issues or the fact that you are trying to connect to a secure paystack page from localhost. What's the latest on this?

**Comment by goodnesskay** [comment]
Okay. so anything I will bbe doign with the laravel/paysstack packagae must not be from localhost?

**Comment by unicodeveloper** [comment]
Try to map it to a valid url that doesn't have localhost in it and try again

**Comment by goodnesskay** [comment]
I will try it and give a feedback. Thanks

**Comment by ibrahimlawal** [comment]
@goodnesskay @unicodeveloper this might also be related to our server requiring TLSv1.2 connections only. Here's the Why: https://developers.paystack.co/v1.0/blog/tls-v12-requirement . A permanent fix would be to update your PHP, OpenSSL and cURL versions. This can be achieved by upgrading WAMP or XAMPP or MAMP if you are using any of them.

**Comment by unicodeveloper** [comment]
Awesome. Thank you @ibrahimlawal for this very useful info!

**Comment by goodnesskay** [comment]
@ibrahimlawal Thanks a lot.. I am going to try it.

**Comment by badruayomaya** [comment]
@ibrahimlawal @unicodeveloper I tried what you both said. I used SSL over a valid FQDN and I upgraded to Openssl 1.0.2 (the tls post says 1.0.1 and above) and yet this issue still persists. 

@goodnesskay is this resolved?

**Comment by badruayomaya** [comment]
@ibrahimlawal @unicodeveloper I'm using PHP 7, CURL 7.51.0, OpenSSL 1.0.2d. Any information would be really helpful

**Comment by badruayomaya** [comment]
One other thing, I have used Paystack with Opencart on this same server this week.

**Comment by ibrahimlawal** [comment]
@badruayomaya Our OpenCart plugin uses a `file_get_contents` fallback which is not encouraged by PSR-2 compliant systems like Laravel. I've not seen many `PHP 7` sites though. You're sure you want to use that in production? `PHP 5.6` is just fine, I guess.

**Comment by badruayomaya** [comment]
@ibrahimlawal @unicodeveloper @goodnesskay 
So I've seen the issue. Apparently (still need to investigate), a CURL request does not get the certificate from the browser, unlike HTTPS. We'll need to manually download the certificate of the site and add it to the PHP ini.

I got the certificate from here: 

https://curl.haxx.se/ca/cacert.pem 

Add the path to php.ini. You should see ;curl.cainfo under [curl]. Uncomment and add the path:

curl.cainfo = "path_to_cert\cacert.pem"

Restart apache and it'll work (at least mine did).

**Comment by ibrahimlawal** [comment]
@badruayomaya Awesome!

**Comment by unicodeveloper** [comment]
@badruayomaya Awesome. Do you mind doing a blog post on that? Many people actually do come across this issue.

**Comment by badruayomaya** [comment]
@unicodeveloper Kool. I'll whip something up shortly.

**Comment by badruayomaya** [comment]
@unicodeveloper @goodnesskay @ibrahimlawal 
So I've written something on my medium page here:

https://medium.com/@badruayomaya/laravel-paystack-curl-error-e21ffbe9b384#.ckqx605b1

Please share as you please.

Cheers,
Badrudeen

**Comment by unicodeveloper** [comment]
Thank you very much @badruayomaya. I should put this in the wiki.

**Comment by goodnesskay** [comment]
Nice @badruayomaya!  I have it all working now. thanks @unicodeveloper

**Comment by unicodeveloper** [comment]
@badruayomaya Just saw your blog post land in my inbox as part of Laravel Daily's newsletter 

<img width="619" alt="screen shot 2017-02-23 at 4 26 38 pm" src="https://cloud.githubusercontent.com/assets/2946769/23265479/01a0acb2-f9e5-11e6-97d8-c10eb8fd1eec.png">

**Comment by badruayomaya** [comment]
@unicodeveloper That's cool. I guess they have some sort of bot scouring the Internet for anything Laravel.
