### ISSUE TITLE
Is Paystack compactible with Laravel 9?

### ISSUE THREAD

**Issue by cletuskingdom** [unicodeveloper/laravel-paystack#159]
I'm trying to install Paystack in Laravel 9 and i'm getting this error: what could be the issue?

![image](https://user-images.githubusercontent.com/38631504/159170239-22035a80-3e7c-4108-b566-4b1bfb8b1a94.png)

**Comment by cletuskingdom** [comment]
![image](https://user-images.githubusercontent.com/38631504/160507416-c2e45d16-6273-400a-bdf1-4396da276cde.png)

**Comment by Tetranyble** [comment]
this package does not support laravel 9 as it's requesting for illuminate/support 6.0.0 => X <=8.0.0. Laravel 9 supports illuminate/support ^9.0.0.

**Comment by Temian1** [comment]
how can I pull your own request please

**Comment by unicodeveloper** [comment]
@Temian1  @Tetranyble @cletuskingdom I just tagged a new release. It supports Laravel 9 now.

**Comment by Temian1** [comment]
good bro
