### ISSUE TITLE
Instruction error - Paystack::getAuthorizationUrl()->redirectNow() method not static

### ISSUE THREAD

**Issue by s-chand** [unicodeveloper/laravel-paystack#16]
Paystack::getAuthorizationUrl()->redirectNow() isn't static. Please do check the ready file

**Comment by unicodeveloper** [comment]
Isn't static? What do you mean? The method is chained but called
statically?

So are you having a non-static error been thrown ?

**Comment by s-chand** [comment]
Apparently PHPStorm has a problem recognizing that construct. Reports an error

Still testing. Will update as soon as results fall through.

Hey Nice work man! Appreciate this effort on integrating Paystack on *our* behalf!

![screen shot 2017-01-12 at 16 38 34](https://cloud.githubusercontent.com/assets/1958765/21896221/e4dd4402-d8e5-11e6-991b-ae6c0fa183ac.png)

**Comment by unicodeveloper** [comment]
@s-chand You are welcome man. Please let me know how it goes, thanks!

**Comment by s-chand** [comment]
@unicodeveloper  I forgot to comeback early enough to notify you that it works seamlessly.
If you do beer, I owe you one.
If you don't, a bottle of water will suffice! 

Jah bles! (y)

**Comment by iamkingsleyf** [comment]
You guys should also make solution to the public, we are having same issue.

**Comment by Tobaino1** [comment]
@s-chand help drop a solution

**Comment by Tobaino1** [comment]
so I came up with a solution, had to create a new instance of Paystack.

```php
public $paystack;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->paystack = new Paystack();
    }
```

then I referenced it like this...

```php
        return $this->paystack->getAuthorizationUrl()->redirectNow();
```


worked for me 😊

**Comment by Akhibemudu** [comment]
@Tobaino1  i got similar error and i followed your instruction, and now am getting this error
`GuzzleHttp\Exception\ClientException` thrown with message "Client error: `POST https://api.paystack.co/transaction/initialize` resulted in a `401 Unauthorized` response:
{
  "status": false,
  "message": "Invalid key"
}
"`
I have done the necessary configuration in my .env file, 
And when i use the sample implementation in the documentation to return Haystack::.....
i get this error
Non-static method Unicodeveloper\Paystack\Paystack::getAuthorizationUrl() should not be called statically
Any suggestion?

**Comment by doubleprincez** [comment]
Exactly the issue i have with it now that made me uninstall it........... 
Non-static method and after making it
` (new Paystack)->getAuthorizationUrl()->redirectNow();`
I get this response
```Client` error: `POST http:\/\/soontec.dev\/payment\/webhook\/transaction\/initialize` resulted in a `404 Not Found` ```
