### ISSUE TITLE
Undefined type 'Unicodeveloper\Paystack\Facades\Paystack'

### ISSUE THREAD

**Issue by iampapagray** [unicodeveloper/laravel-paystack#168]
Thank you for this library.

I'm using this on Laravel 9.
i added `'Paystack' => Unicodeveloper\Paystack\Facades\Paystack::class,` to my `config/app.php` in the `aliases` array like so:
```
'aliases' => Facade::defaultAliases()->merge([
        'Carbon' => Illuminate\Support\Carbon::class,
        'Paystack' => Unicodeveloper\Paystack\Facades\Paystack::class,
    ])->toArray(),
```

However, in my controller when i do `Paystack::getAllCustomers()` VSCode underlines `Paystack`. 
And intelliphense gives error message as `Undefined type 'Unicodeveloper\Paystack\Facades\Paystack'`

Is there something i'm missing? Kindly help

**Comment by goodmuyis** [comment]
Your controller is missing `**use Paystack;**` at the top

**Comment by ucodetech** [comment]
I'm having same issues here even when i have referenced the use Paystack at the top

**Comment by goodmuyis** [comment]
> I'm having same issues here even when i have referenced the use Paystack at the top

Did you...


```
Also, register the Facade like so:

'aliases' => [
    ...
    'Paystack' => Unicodeveloper\Paystack\Facades\Paystack::class,
    ...
]
```

**Comment by ucodetech** [comment]
It's working now thanks
