### ISSUE TITLE
Class Paystack not found

### ISSUE THREAD

**Issue by wapnen** [unicodeveloper/laravel-paystack#17]
cannot find class Paystack . I have registered the package in the providers and aliases in my app\config. also after running php artisan publish, it says "nothing to publish for tags". Tried using the class without the alias and it still cant find it.

**Comment by wapnen** [comment]
never mind. apparently i was using cached config files. i ran "php artisan config:clear" and reran php artisan publish. Everything seems to be working fine now

**Comment by ejalee** [comment]
> never mind. apparently i was using cached config files. i ran "php artisan config:clear" and reran php artisan publish. Everything seems to be working fine now

You mean php artisan vendor:publish
