### ISSUE TITLE
How to give callback url per transaction

### ISSUE THREAD

**Issue by tommygr8** [unicodeveloper/laravel-paystack#20]
From the documentation, you can only register callback url on the dashboard unlike the codeigniter api where you can specify callback url per transaction. I may have many transactions from different website, how do i specify callback for each transaction

**Comment by tommygr8** [comment]
I just saw it in the code that there is a callback_url in the parameter and so one can pass the callback_url as part of the hidden field and the value to be the callback url you want it return to after the payment. 
Moreso, passing the value in the hidden field is not secured as one can change the the amount value from the inspect element.  What i did is to remove the hidden field and in the controller, i have to add the parameters to request  before calling Paystack::getAuthorizationUrl()->redirectNow()

**Comment by Francis-Njoku** [comment]
@tommygr8 Please how did you pass the callback_url as part of the hidden field, could you drop a snippet.
Thanks

**Comment by tommygr8** [comment]
You can add the callback url to the request before getAuthorizationUrl

function pay(Request $request)
{

                       ..... 
                           $request->request->add([
									'callback_url' =>"my callback",
								]);
								
								
        return \Paystack::getAuthorizationUrl()->redirectNow();
}

or use  <input type="hidden" name="callback_url" value="my callback_url">

**Comment by tommygr8** [comment]
function pay(Request $request)
{

                   ..... 
                       $request->request->add([
								'callback_url' =>"my callback",
							]);
							
							
    return \Paystack::getAuthorizationUrl()->redirectNow();
}

or add hidden field and name="callback_url" and value="callback_ur;"
 &lt; input type="" name="callback_url" value="callback_ur" &gt;

**Comment by Francis-Njoku** [comment]
I will try it
