### ISSUE TITLE
Testing API connection

### ISSUE THREAD

**Issue by Khokavim** [unicodeveloper/laravel-paystack#24]
Using Laravel 5.4 and I just requird laravel-paystack plus necessary details. Getting this error presently

Client error: `POST https://api.paystack.co/transaction/initialize` resulted in a `400 Bad Request` response:
{
"status": false,
"message": "Plan not found"
}

Kindly assist me here please

**Comment by afolabiabass** [comment]
Is it a recurring transaction?

**Comment by Khokavim** [comment]
yes it is, but all is fixed now. Nice package

**Comment by kidikudazi** [comment]
@Khokavim how did you solvw this issue?

**Comment by kidikudazi** [comment]
solve*

**Comment by odion-cloud** [comment]
how did you solve this please having same issue

**Comment by donejeh** [comment]
if you do have this error something try your live keys

> how did you solve this please having same issue
