### ISSUE TITLE
Should not use this package?

### ISSUE THREAD

**Issue by shirshak55** [unicodeveloper/laravel-paystack#37]
It seems in example you are writing secret key inside form html. Am i wrong but i think secret key is only for server not for user side right?????????????

**Comment by kingflamez** [comment]
Secret key is saved in your .env, not the HTML form

**Comment by bloggervista** [comment]
@kingflamez see read me last section there is written env("SECRET KEY") like that

**Comment by bloggervista** [comment]
@kingflamez 

see this in readme

```
<input type="hidden" name="key" value="{{ config('paystack.secretKey') }}"> {{-- required --}}
```

I guess its major security issue and should be patched soon.

**Comment by Hursteen** [comment]
> 
> 
> @kingflamez see read me last section there is written env("SECRET KEY") like that

remove the input form field for secretKey and everything will still work fine.
