### ISSUE TITLE
In paystackServiceProvider.php line 34 Call to undefined function Unicodeveloper\Paystack\config_path()

### ISSUE THREAD

**Issue by marvinjude** [unicodeveloper/laravel-paystack#39]
I am using this package in my lumen API, I have registered the service provide like so

```
$app->register(Unicodeveloper\Paystack\PaystackServiceProvider::class) ;
```
And also added the paystack.php to my config folder.  But I still keep getting this error 

```
In paystackServiceProvider.php line 34 Call to undefined

```

**Comment by marvinjude** [comment]
```
In paystackServiceProvider.php line 34 Call to undefined function Unicodeveloper\Paystack\config_path()
```

**Comment by unicodeveloper** [comment]
Hello @marvinjude. What's your use case? I see no reason why you should this particular package for an API.

What exactly are you trying to achieve with Paystack on your Lumen API?

**Comment by marvinjude** [comment]
Hmm, @unicodeveloper . Basically I am trying to force the whole payment processing with Paystack into the API, something also tells me this is inappropriate.

**Comment by blessedmadukoma** [comment]
Good day, I am trying to integrate Paystack into Lumen but I got this same error. Is there a way to fix it? thank you.
