### ISSUE TITLE
When I publish The service provider this is what I get

### ISSUE THREAD

**Issue by emekaorjiani** [unicodeveloper/laravel-paystack#49]
php artisan vendor:publish --provider="Unicodeveloper\Paystack\PaystackServiceProvider"

                                                                                   
  [Symfony\Component\Debug\Exception\FatalThrowableError]                          
  Call to undefined method Unicodeveloper\Paystack\Facades\Paystack::isDeferred()

**Comment by derskeal** [comment]
DO you have this in your app.php config file?

`'Paystack' => Unicodeveloper\Paystack\Paystack::class,`

If you do, remove it.

**Comment by emekaorjiani** [comment]
Fixed! Thanks
