### ISSUE TITLE
Does not work for laravel 5.5 and above (5.6)

### ISSUE THREAD

**Issue by Thirdwrist** [unicodeveloper/laravel-paystack#53]
I have tried using this package on laravel 5.5 and 5.6 but it keeps returning the curl 3 error, I have used this package on 5.4 and I had no problem. But that isn't the same in the former. 

![image](https://user-images.githubusercontent.com/16085561/42749672-5ab237d0-88dc-11e8-9a09-905ef1e6ac44.png)
Please do check this out:
Steps to reproduce:

requirements:
1. Windows computer
2. Apache engine
3. Localhost
4. Laravel 5.5 and above

Steps: 
1. Install laravel 5.5 or above
2. Require the unicodedeveloper paystack package
3. Set it up as in the readme

try to Initialize a payment with the default inputs as provided in the readme

#26

**Comment by taghwo** [comment]
Lost every hair on my head today. Can't find any solution to this

**Comment by Thirdwrist** [comment]
A friend of mine found a solution to it, you can reach him out on twitter @awulonu_obinna

I ended up using another package for this.

https://github.com/yabacon/paystack-php

**Comment by taghwo** [comment]
let me try that. Thanks

**Comment by taghwo** [comment]
is it the package that has the curl issue or it's the laravel version?

**Comment by taghwo** [comment]
The document on that package is head shrinking

**Comment by Thirdwrist** [comment]
At the moment when I had the issue, time wasn't on my side to debug deeply so I just switched package.

**Comment by taghwo** [comment]
Think i have found the solution, it's working now

**Comment by Thirdwrist** [comment]
Share please, was it with the help of the friend I suggested?

**Comment by taghwo** [comment]
Did a few things,i will go back on all the steps and post here...

**Comment by Thirdwrist** [comment]
Awesome

**Comment by taghwo** [comment]
okay so i took out every change i made while trying to debug the error from php.ini to  the getting the api full path, i removed everything. Surprisingly it worked as it was then when the curl error was popping up . The only thing i see is, after the set up is complete you need to run config:cache and hit ctrl F5 to refresh

**Comment by ladaposamuel** [comment]
I had this error too then i read the Readme file again and ran this
`php artisan vendor:publish --provider="Unicodeveloper\Paystack\PaystackServiceProvider"`
It fixed the issue.

**Comment by gisthive** [comment]
> I had this error too then i read the Readme file again and ran this
> `php artisan vendor:publish --provider="Unicodeveloper\Paystack\PaystackServiceProvider"`
> It fixed the issue.

This fixed the issue instantly. Thanks

**Comment by ajayidavid99** [comment]
> I had this error too then i read the Readme file again and ran this
> `php artisan vendor:publish --provider="Unicodeveloper\Paystack\PaystackServiceProvider"`
> It fixed the issue.

So should I read it again! Just tell us what you discovered when you read it. (laughable!)
You may need to reopen your application then re-run: 
`php artisan vendor:publish --provider="Unicodeveloper\Paystack\PaystackServiceProvider"`
for you to notice  paystack.php copied into your config folder but this doesn't solve the above question

**Comment by banklan** [comment]
i am having this issue and still cannot resolve with all the suggestions

**Comment by unicodeveloper** [comment]
Closing this issue because it's almost a year old and people have gotten solutions
