### ISSUE TITLE
Passing Phone Number, First name and Last name with the email

### ISSUE THREAD

**Issue by chidiesobe** [unicodeveloper/laravel-paystack#59]
Hello 
i have been trying to pass phone number , name and email to the transaction page with no success, has anyone been able to do this.
For example the amount hidden field is this 
<input type="hidden" name="amount" value="{{$amount * 100}}"> {{-- required in kobo --}}
When you view the array  gotten from  dd($paymentDetails);  you see that first name , last name name and phone returns null regardless of having an input like this one below, nothing gets sent

<input type="text" name="phone" value="{{Auth::user()->phonenumber}}">

**Comment by derskeal** [comment]
Does your input have a `name` attribute?

**Comment by mcdust** [comment]
Yes and it still does not work

**Comment by Hursteen** [comment]
I encounter similar issue. how did you find your way around it ?

**Comment by derskeal** [comment]
@mcdust Can u give us more info?

**Comment by Hursteen** [comment]
**A way around it**. I collected the fullname as a form field then i used javascript to collect the fullname value, and then append it to the metadata value (when you mousedown the submit button) before submitting the form. so the information would be available together with the metadata value when i get a success message from the paystack api.

**Comment by taghwo** [comment]
Any solution to this yet?

**Comment by taghwo** [comment]
Just use the metadata array like so 
first_Name => auth::user()->first_Name,...
If you dd($paymentDetails); you would notice the first_Name will be there in the array metadata and you can easily access it like so in your payment controller ($paymentDetails ['data']['metadata'][first_Name]); 
I found out also you have to add the callback route to your callback url on your paystack dashboard (yoururl.com or .test/payment/callback)
And webhook url on paystack dashboard will be (yoururl.com or .test/pay)...Hope this helps!

**Comment by taghwo** [comment]
['first_Name']*

**Comment by Emizy** [comment]
@Hursteen can you give us a sample code,have been trying it but not working

**Comment by taghwo** [comment]
Sorry that my code is not formatted properly

**Comment by Francis-Njoku** [comment]
@taghwo Thanks for this

**Comment by Emizy** [comment]
@taghwo Thanks ,I will surely try it and give feedback

**Comment by Emizy** [comment]
@taghwo i actually tried it,its only works when i used Auth::user()->id  but its doesnt work if what i want to embedded inside the metadata is part of the form ,for example

i want to add this Data network with name="network" inside the metadata
<input id="network" type="text" class="form-control" name="network" readonly="true" required>

when is used your method 
<input type="hidden" name="metadata" value="{{ json_encode($array = ['Network' => $request->input('network'))]) }}" >
its gives an Undefined Variable Error.

Can you kindly give a clue on how to do it.Thanks

**Comment by Francis-Njoku** [comment]
@Emizy Check for bugs on your payment page

**Comment by taghwo** [comment]
Oh sorry my bad you should not use $request in view. Will edit my initial post. How do you get the network? User inputs it?

**Comment by Emizy** [comment]
User inputs it? Yes(its a select option drop down)..and the input field is on the same form with the metadata hidden input field

**Comment by taghwo** [comment]
To test,assign any value to the network key. No $request now and check if it returns with the metadata

**Comment by Emizy** [comment]
Its actually worked when I passes dummy data, but how about a scenerio where by I need the user to specify the network type for the data subscription he want to buy...

Using that scenerio ,how can I affix the data inside the metadata..

Have been trying to figure this out for some weeks now...Still getting stucks in it..

**Comment by taghwo** [comment]
Either you use JS or you do what you should have done in the 1st place. 

Change your payment flow pattern. Add a confirmatory or checkout page. Is this better for UX? I think so.

 The user can atleast have another chance ti actually see they clicked the right network or they press back if they made a mistake.

Payment page should just have a normal form with action="/checkout" or you can name a route for it as you wish.

In checkout or confirmation controller you capture the selected network input and assign it to a variable.

And return view("/checkout or confirmation")->with('selectedNetwork', "$selectedNetwork).

The Checkout or confirmation page will hold the paystack form.

Since you now have the the selected network available in the checkout or confimation controller,you can easily pass $selectedNetwork as value for the network key in the matadata.

**Comment by ekpono** [comment]
Here is my implementation.

`public function __construct() {
    $this->paystack = new Paystack();
}
public function makePaymentRequest(Request $request)
    {
        $this->paystack->createCustomer([
            $request['fname'] = 'my first name',
            $request['lname'] = 'my last name',
            $request['phone'] = '0828347343435',
            $request['email'] = 'amb@gmaiy.com'
        ]);
        
        $reference = $request['reference'] = $this->paystack->genTranxRef();
        $request['amount'] = request()->amount;
        return $this->paystack->getAuthorizationUrl()
            ->redirectNow()
            ->with(['message' => 'You have successfully made payment]);
    }`

**Comment by leafmanDHunter** [comment]
If you are faced with passing custom field to metadata, Here is how I solved mine using javascript
` <input type="hidden" name="metadata[]" id="metadata" >`
`<button type="submit" class="btn btn-primary" onmousedown="fetchMetaValues()">Pay Now</button>`
JS 
` function fetchMetaValues() {
        let metadata =  document.getElementById('metadata');
        let fullname = document.getElementById('fullname').value;
        let phone_number = document.getElementById('phone_number').value;
        let unit_price = document.getElementById('unit_price').value;
        let units = document.getElementById('units').value;
         let fid = {'name':fullname, 'phone': phone_number, 'unit':units, 'price':unit_price};
        metadata.value = JSON.stringify(fid);
    }`

**Comment by leafmanDHunter** [comment]
`if ($paymentDetails['data']['status'] === 'success')
        {
            $donor_name = $paymentDetails['data'] ['metadata']['fullname'];
            $donor_email = $paymentDetails['data'] ['metadata']['email'];
            $donor_phone = $paymentDetails['data'] ['metadata']['phone_number'];
            $unit_pricef = $paymentDetails['data'] ['metadata']['unit_price'];
            $units = $paymentDetails['data'] ['metadata']['units'];
            $amount = $paymentDetails['data'] ['amount'];

            dd($donor_phone);
        }`

**Comment by goodmuyis** [comment]
Some having similar issue in 2020 or beyond...
I discovered or assumed that `json_encode()` is conflicting with `htmlspecialchars()` when you try to `{{ $user->last_name}}` this may not be true, but it is problematic for me so here is how i solve mine
```
<?php
$meta = "{'First_Name':'$user->first_name','Last_Name':'$user->last_name','Student_Email':'$user->email','Phone No':'{$user->profile->phone_no}'}";
?>
.
.
.
<input type="hidden" name="metadata" value="{{ json_encode($meta) }}" >
```

So everything  workout well. And Yes `<?php ?>` tag will work inside blade template

**Comment by Abdulrazakrogo** [comment]
@goodmuyis Thank you for this. It works!
