### ISSUE TITLE
Non-static method Unicodeveloper\Paystack\Paystack::genTranxRef() should not be called statically

### ISSUE THREAD

**Issue by OLayemii** [unicodeveloper/laravel-paystack#68]
I keep getting this error 
`Non-static method Unicodeveloper\Paystack\Paystack::genTranxRef() should not be called statically` when i try setting up the library according to its doc
This is what gives the error

`<input type="hidden" name="reference" value="{{ Unicodeveloper\Paystack\Paystack::genTranxRef() }}">`

Am trying this on Laravel 5.7

**Comment by dbkonxepts** [comment]
Hi Olayemii,

1. In your controller make sure you are importing.
`use Paystack;` 
and not 
`use Unicodeveloper\Paystack\Paystack;`

2. Then in your pay method i.e     
```
    public function redirectToGateway(Request $request)
    {
        :
        :
        $request->reference = Paystack::genTranxRef();
        :
        return Paystack::getAuthorizationUrl()->redirectNow();
    }
```

**Comment by OLayemii** [comment]
> Hi Olayemii,
> 
> 1. In your controller make sure you are importing.
>    `use Paystack;`
>    and not
>    `use Unicodeveloper\Paystack\Paystack;`
> 2. Then in your pay method i.e
> 
> ```
>     public function redirectToGateway(Request $request)
>     {
>         :
>         :
>         $request->reference = Paystack::genTranxRef();
>         :
>         return Paystack::getAuthorizationUrl()->redirectNow();
>     }
> ```

using `use Paystack` causes `Class 'Paystack' not found`

**Comment by dbkonxepts** [comment]
Alright, it means you didn't register the Facade.
To do this, open the `app.php` file in **config\\** folder, scroll down to `aliases` section and append like so:
```
'aliases' => [
    ...
    'Paystack' => Unicodeveloper\Paystack\Facades\Paystack::class,
    ...
]
```

**Comment by OLayemii** [comment]
> Alright, it means you didn't register the Facade.
> To do this, open the `app.php` file in **config\** folder, scroll down to `aliases` section and append like so:
> 
> ```
> 'aliases' => [
>     ...
>     'Paystack' => Unicodeveloper\Paystack\Facades\Paystack::class,
>     ...
> ]
> ```

Adding that and changing all ` use Unicodeveloper\Paystack\Facades\Paystack` to `use Paystack` gives `class laravel-paystack not found`. the docs says that step should be skipped for laravel versions above 5.5 ..or not?

**Comment by dbkonxepts** [comment]
_Ignore the doc._
It shouldn't be skipped. 

If you `use Unicodeveloper\Paystack\Paystack;` then you would have to create an instance whenever you need to call the **_Paystack_** class i.e `$paystack = new Paystack();` because the methods are not static.

However you can avoid the whole instance thing, (that's one of the reason for the "Facade" keys) by adding the alias as I have sent it. 
Then in anywhere you can call

`Paystack::functionName()` 

instead of

`$paystack = new Paystack();`
`$paystack->functionName();`

**Comment by OLayemii** [comment]
> _Ignore the doc._
> It shouldn't be skipped.
> 
> If you `use Unicodeveloper\Paystack\Paystack;` then you would have to create an instance whenever you need to call the **_Paystack_** class i.e `$paystack = new Paystack();` because the methods are not static.
> 
> However you can avoid the whole instance thing, (that's one of the reason for the "Facade" keys) by adding the alias as I have sent it.
> Then in anywhere you can call
> 
> `Paystack::functionName()`
> 
> instead of
> 
> `$paystack = new Paystack();`
> `$paystack->functionName();`

Fixed it using your method, i just needed to register the provider.
Having a whole new different error though.

**Comment by dbkonxepts** [comment]
Feel free to drop it. 
Always happy to help.
