### ISSUE TITLE
getPaymentData() doesn't check if transaction reference has been given value

### ISSUE THREAD

**Issue by Dazco** [unicodeveloper/laravel-paystack#76]
Users can use the same transaction reference to perform multiple transactions by refreshing the callback url if an error occcurs.

**Comment by ajayidavid99** [comment]
What you mean by given value? getPaymentData() gives you the details of a transaction even if it was conducted 30 years ago, whether the services has been delivered or not should be validated by you.

**Comment by josephtesla** [comment]
Yes, but this wasn't stated in the documentation and can lead to real security issues for first time users.
