### ISSUE TITLE
cURL error

### ISSUE THREAD

**Issue by princenazi** [unicodeveloper/laravel-paystack#8]
keep receiveing an error like this,

cURL error 35: Unknown SSL protocol error in connection to api.paystack.co:443 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

any help?
using laravel 5.3

**Comment by unicodeveloper** [comment]
Are you using wamp?

**Comment by princenazi** [comment]
yeah...figured out it was just a network problem...thanks..Nice work btw
p.s:It'ld be waay cooler if u added codes for subscriptions and plans

**Comment by Mrchux** [comment]
I'm getting the same error. I'm using xampp.

**Comment by chiwex** [comment]
error from secret key or public key

**Comment by unicodeveloper** [comment]
People using xampp or wamp have had this kind of error before. I'll try to look out for what they did. I can't remember the solution they deployed right now.

**Comment by princenazi** [comment]
@Mrchux , i had that error before because i did not have an active internet connection. After connecting to my laptop to the internet it works fine, the paystack api requires an active internet connection to work.

**Comment by princenazi** [comment]
@chiwex  The secret key has to be input correctly in the secret key field, and the public key input correctly in the public key field of your config or preferably .env file. This normally shudnt be an issue, refresh these keys if problem persists.

**Comment by goodnesskay** [comment]
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) any help please? My internet connection is fine and I am using xampp. what could be the issue please?
