### ISSUE TITLE
Request for update to version 6.0.*

### ISSUE THREAD

**Issue by doubleprincez** [unicodeveloper/laravel-paystack#80]
My Laravel application version is 6.0.3 and would like to use paystack without downgrading. Please help

**Comment by dmarcos89** [comment]
Any update on this one?
Thanks

**Comment by phemorah** [comment]
Hello guyz, 

You can check the following repository to find the working laravel 6 paystack:

Https://github.com/phemorah/laravel-paystack.

It works with any latest Laravel framework.

Cheers!

**Comment by Dilpenny** [comment]
Laravel 7.* seems not to work

**Comment by unicodeveloper** [comment]
Done. Upgrade to the latest version. version 1.0.4 @Dilpenny  @dmarcos89 @doubleprincez
