### ISSUE TITLE
I am trying to install Paystack on Laravel 6.0.*  but it is not installing, What do i do?

### ISSUE THREAD

**Issue by ify-kaka** [unicodeveloper/laravel-paystack#82]
I am trying to install Paystack on Laravel 6.0.*  but it is not installing, What do I do?

**Comment by Ujahmycine** [comment]
Use laravel 5.8 for now. I believe the team is working on it

**Comment by kizinho** [comment]
noticed the issue, have mailed prosper or we fix the issues

**Comment by Bazzly** [comment]
not compatible for now . use laravel 5.8 . you can go to your composer and include or change to this       "laravel/framework": "5.8",

**Comment by shoutershub** [comment]
> 
> 
> not compatible for now . use laravel 5.8 . you can go to your composer and include or change to this "laravel/framework": "5.8",

Don't do that man, don't

**Comment by bere6255** [comment]
for laravel 6.0 use curl to perform all calls to pay-stack see documentation https://developers.paystack.co/v2.0/reference#initialize-a-transaction
