### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by Dilpenny** [unicodeveloper/laravel-paystack#86]
Whenever i try to pay i get this error:
Client error: `POST https://api.paystack.co/transaction/initialize` resulted in a `401 Unauthorized` response: { "status": false, "message": "Invalid key" }

**Comment by Bazzly** [comment]
this you use this   Unicodeveloper\Paystack\Facades\Paystack; in your payment controller ??

**Comment by bere6255** [comment]
@Dilpenny the message is clear now you public or private key is not valid

**Comment by bere6255** [comment]
> @bere6255 I am querying my keys from a database table then used Config::set
> ("variablename", value) to set the value of the keys on the paystack config file. This however give error 401. But when I copy and paste the same queried key directly to paystack config file the request fires with 200 status code.

Best practice do not store keys in database use env files and ignore them from commit that will solve your problem

**Comment by EmmyGuy** [comment]
@bere6255 thanks for your response. But the situation here warrants the choice. Scenario: I have SaaS where different users represents a different business on my paystack account. These users have different keys as such I want payment going to individual business bank account. My best shot is to dynamical set keys before making API call. 

Any other way of handling such case shall be appreciated.

**Comment by bere6255** [comment]
> @bere6255 thanks for your response. But the situation here warrants the choice. Scenario: I have SaaS where different users represents a different business on my paystack account. These users have different keys as such I want payment going to individual business bank account. My best shot is to dynamical set keys before making API call. 
> 
> Any other way of handling such case shall be appreciated.

Handle all disbursement from a single account and manage all your business accounts internally, the you will be able to track when things go wrong for customer support

**Comment by EmmyGuy** [comment]
thanks for the heads up @bere6255. but I got it done by writing it to the environment variable the fetch the same from the config... that way, every client payment goes to her account under a business on the paystack platform.

**Comment by bere6255** [comment]
> thanks for the heads up @bere6255. but I got it done by writing it to the environment variable the fetch the same from the config... that way, every client payment goes to her account under a business on the paystack platform.

Soft🎉
