### ISSUE TITLE
not install in laravel v6

### ISSUE THREAD

**Issue by WaleedSKamel** [unicodeveloper/laravel-paystack#88]
can you update this package

**Comment by emmanueletukudo** [comment]
I have the same issue, it is not installing on Laravel v6.

**Comment by phemorah** [comment]
You can check the following repository to find the working laravel 6 paystack:

Https://github.com/phemorah/laravel-paystack.

It works with any latest Laravel framework.

Cheers!

**Comment by unicodeveloper** [comment]
Done. Upgrade to the latest version. version 1.0.4
