### ISSUE TITLE
Duplicate transaction reference

### ISSUE THREAD

**Issue by reigningkingforever** [unicodeveloper/laravel-paystack#89]
I want to believe this is the line that produces the transaction reference..
`<input type="hidden" name="reference" value="{{ Paystack::genTranxRef() }}"> {{-- required --}}`
I got this error today.
![image](https://user-images.githubusercontent.com/19579886/70360189-0eb65e00-187e-11ea-88e8-14a1b049e931.png)

**Comment by Bazzly** [comment]
i am having the same error trying to set up payment on laravel 5.8

**Comment by reigningkingforever** [comment]
I solved it by creating a unique transaction reference of my own, using the
date & time, which is unlikely to ever be a duplicate.

You should try that
