### ISSUE TITLE
Paystack Inline

### ISSUE THREAD

**Issue by elmage** [unicodeveloper/laravel-paystack#9]
Please i'd like some info on how to use this package with paystack inline on laravel
It throws Exception if i try. Thanks in advance.

**Comment by elmage** [comment]
> Ermmm..It depends on what you mean by "Inline". Can you shed some more light on 
> that?

The pop up version of paystack. I could only use paystack standard. 

[https://developers.paystack.co/docs/paystack-inline](url)

**Comment by unicodeveloper** [comment]
This package doesnt really provide that. I thought paystack had a js script just like stripe for that. Have you checked?

**Comment by elmage** [comment]
yea they do. but can't i use the same call back function for both inline and standard?

**Comment by unicodeveloper** [comment]
I'm not sure, never tried the inline before

**Comment by elmage** [comment]
Okay thanks.
