### ISSUE TITLE
Not compatible with Laravel v6

### ISSUE THREAD

**Issue by emmanueletukudo** [unicodeveloper/laravel-paystack#90]
You need to update the package.

**Comment by nanichang** [comment]
Is the support for Laravel 6.* coming anytime soon?

**Comment by emmanuelJet** [comment]
@unicodeveloper when will the support for laravel 6.* roll in?

**Comment by phemorah** [comment]
Hello guyz, 

I finally developed a working Laravel PayStack package that is compatible with any latest version of Laravel framework. 

You can check the following repository to find the working laravel 6 paystack:

Https://github.com/phemorah/laravel-paystack.

It works with any latest Laravel framework.

Cheers!

**Comment by emmanuelJet** [comment]
> @unicodeveloper when will the support for laravel 6.* roll in?

Thanks @unicodeveloper

**Comment by unicodeveloper** [comment]
Done. Upgrade to the latest version. version 1.0.4
