### ISSUE TITLE
How To Handle Array From Laravel Payment Gateway

### ISSUE THREAD

**Issue by Greatlegend12** [unicodeveloper/laravel-paystack#91]
![IMG_20200101_171324](https://user-images.githubusercontent.com/44454392/71643459-3a303b00-2cba-11ea-8448-516dd18a7a89.jpg)

I got the array of information in the above screenshot after integration and making payments. Trying to add them to the database and update and and user information, I'm finding it hard. Please help me out.

**Comment by odutolaabisoye** [comment]
Try this

    public function handleGatewayCallback()
    {
        $paymentDetails = Paystack::getPaymentData();
      $user = User::find(Auth::id());
      $user->column_name = date("Y-m-d H:i:s",strtotime($paymentDetails['data']['paidAt']));
    $user->another_column_name= $paymentDetails['data']['plan_object']['name'];
     $user->save();

     return redirect ( route ('welcome'));

    }

If you have any question let me know.

**Comment by Greatlegend12** [comment]
I used it, I got this error
![Screenshot (184)](https://user-images.githubusercontent.com/44454392/71688554-53131c00-2da0-11ea-8fdf-f2ecd995bef9.png)

**Comment by Greatlegend12** [comment]
see full detail call back
![Screenshot (185)](https://user-images.githubusercontent.com/44454392/71689566-a5edd300-2da2-11ea-9abd-d4cfef7cb48c.png)
![Screenshot (186)](https://user-images.githubusercontent.com/44454392/71689568-a5edd300-2da2-11ea-8e9d-a7feeab98683.png)

**Comment by odutolaabisoye** [comment]
Can I see your code
This is the way it work, I assume you're saving into the user table and you have registered your method in your route 
So to get the data, I pass the payment data into a new variable 
$paymentDetails = Paystack::getPaymentData();

I get the user info, 
$user = User::find(Auth::id());

This save the data into the column, there are 3 level 
First level is data, to get data id 
$paymentDetails['data']['id'] ;
$paymentDetails['data']['authorization'] ['last4'] 
$paymentDetails['data']['forst_name'] 

You can save it like this 
$user->another_column_name= $paymentDetails['data']['authorization'] ['last4'] 
 $user->save();

Paste your code here and your route, if you have any error.

**Comment by Greatlegend12** [comment]
These are my codes, i created a table called payments, running the code, i get error 500 as in the screenshoot


![Screenshot (203)](https://user-images.githubusercontent.com/44454392/71787207-67138380-3015-11ea-8d01-cbe12ec077f4.png)
![Screenshot (204)](https://user-images.githubusercontent.com/44454392/71787209-6975dd80-3015-11ea-9cc3-aa780ec558e4.png)
![Screenshot (205)](https://user-images.githubusercontent.com/44454392/71787210-6975dd80-3015-11ea-82f9-c8d2bfd9d257.png)
![Screenshot (206)](https://user-images.githubusercontent.com/44454392/71787211-6a0e7400-3015-11ea-9a37-a41700800ba2.png)

**Comment by Greatlegend12** [comment]
These are my codes, i created a table I called payments. Cant save, I'm getting error 500 as in the screenshot

![Screenshot (206)](https://user-images.githubusercontent.com/44454392/71787343-da69c500-3016-11ea-9860-9ca36cedef90.png)
![Screenshot (207)](https://user-images.githubusercontent.com/44454392/71787344-da69c500-3016-11ea-8471-bd730cdfd37d.png)
![Screenshot (208)](https://user-images.githubusercontent.com/44454392/71787345-db025b80-3016-11ea-92fd-d7380ff7e6b0.png)
![Screenshot (209)](https://user-images.githubusercontent.com/44454392/71787346-db025b80-3016-11ea-95e9-08634dbdeaeb.png)

**Comment by odutolaabisoye** [comment]
Have you registered your callback URL on paystack  https://dashboard.paystack.com/#/settings/developer
https://websitename.com/payment/callback

**Comment by Greatlegend12** [comment]
Yes,  have registered my callback on paystack

**Comment by odutolaabisoye** [comment]
Please change to      return redirect ( route ('home'));

**Comment by Greatlegend12** [comment]
I want to save the details in 'payments' table, not the user table

**Comment by odutolaabisoye** [comment]
You need to create a relationship between user table and payment table. Then import your model. You can now use orm or query to create a new record at each instances.

**Comment by Greatlegend12** [comment]
How do I create the relationship, please help

**Comment by odutolaabisoye** [comment]
In user model, do this
    public function payments(){
        return $this->hasMany(Payment::class);
    }

In Payment model, do this
    public function user()
    {
        return $this->belongsTo(User::class);
    }

Do the rest in your controller
